### ISSUE TITLE
import collision with logrus

### ISSUE THREAD

**Issue by warroyo** [meatballhat/negroni-logrus#28]
it looks like `Sirupsen/logrus` has updated the import path to have a lowercase "s" I am now seeing this error

`case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"`

could this be updated here: https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L9

and here : https://github.com/meatballhat/negroni-logrus/blob/master/middleware_test.go#L12

**Comment by gravis** [comment]
Hi please double check, the change has been reverted since a long time.

Sent from my iPhone

On 19 mai 2017, at 14:18, Will Arroyo <notifications@github.com> wrote:

it looks like Sirupsen/logrus has updated the import path to have a
lowercase "s" I am now seeing this error

case-insensitive import collision: "github.com/Sirupsen/logrus" and "
github.com/sirupsen/logrus"

could this be updated here:
https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L9

and here :
https://github.com/meatballhat/negroni-logrus/blob/master/middleware_test.go#L12

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/meatballhat/negroni-logrus/issues/28>, or mute the
thread

**Comment by warroyo** [comment]
@gravis are you saying the chnage has been reverted in the Siupsen/logrus code?

**Comment by gravis** [comment]
Yup. I'm maintaining several logrus hooks (airbrake, postgresql, etc. ) and
I've seen this PR 3 times already ;)
They have been closed without merging.

Sent from my iPhone

On 19 mai 2017, at 14:36, Will Arroyo <notifications@github.com> wrote:

@gravis <https://github.com/gravis> are you saying the chnage has been
reverted in the Siupsen/logrus code?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/meatballhat/negroni-logrus/issues/28#issuecomment-302779266>,
or mute the thread

**Comment by warroyo** [comment]
oh ok, thank you! I think i just need to update my dependency then.

**Comment by gravis** [comment]
FYI:

https://github.com/gemnasium/logrus-airbrake-hook/pull/2
https://github.com/gemnasium/logrus-graylog-hook/issues/23

Sorry for this mess :)
I'm closing this, as there's nothing we can do.
Thanks

**Comment by warroyo** [comment]
@gravis I looked into it a bit more since I am still having conflicts and `sirupsen/logrus` did convert to use lowercase . could this package please convert to lowercase? otherwise conflicts will continue to happen. here is another issue with a direct response from sirupsen stating lowercase is the way to  go.

https://github.com/bshuster-repo/logrus-logstash-hook/issues/32

**Comment by gravis** [comment]
Ok, so apparently, they have rolled-back the rollback: https://github.com/bshuster-repo/logrus-logstash-hook/issues/32#issuecomment-303195028

I have asked for clarification in https://github.com/sirupsen/logrus/pull/384

Thanks

**Comment by warroyo** [comment]
@gravis any update on getting this fixed?

**Comment by gravis** [comment]
I will update this package with the lower-case import path this week, I had some client emergencies last days :(
Sorry for the delay.

**Comment by gravis** [comment]
Since it will probably break a lot of things, I have an idea: What about using http://gopkg.in/sirupsen/logrus.v0 as the import path. We're sure it will work for everyone that way.
@sirupsen, what do you think of that?

**Comment by gravis** [comment]
and btw, Logrus is stable enough to be called v1 instead of v0 (@sirupsen: it takes a v1.x.x tag in the repo for that). I know improvements are coming, but they can be shipped in a V2, since they are improvements.

**Comment by gravis** [comment]
@meatballhat, regarding the overall movement on this, I'm updating the import path to `github.com/sirupsen/logrus`. It will probably break some builds, but we can't keep plugins on the "wrong" path. Thanks
